### ISSUE TITLE
깃에서 예제 코드 조사

### ISSUE THREAD

**Issue by hbseo** [alchon/simpsons#4]
계산기 코드 찾아서 댓글 ㄱㄱ

**Comment by hbseo** [comment]
https://github.com/benoitvallon/react-native-nw-react-calculator
언어 - 자바스크립트
ios, android, desktop, web site 구동 가능

**Comment by hellogaon** [comment]
https://github.com/Moosemorals/Calculator
언어 - 자바

**Comment by hellogaon** [comment]
https://github.com/hrant1000/Calculator
언어 - 자바

**Comment by hellogaon** [comment]
https://github.com/roryokane/CalcuDoc
언어 - 자바
