### ISSUE TITLE
Exception occurs when type parentheses only

### ISSUE THREAD

**Issue by inureyes** [alchon/simpsons#40]
* Exception occurs when type parentheses only
 * See screenshot:

<img width="432" alt="screen shot 2016-12-20 at 2 57 41 pm" src="https://cloud.githubusercontent.com/assets/949915/21339725/c3b6f864-c6c4-11e6-83eb-51508561bc1c.png">
<img width="689" alt="screen shot 2016-12-20 at 2 57 43 pm" src="https://cloud.githubusercontent.com/assets/949915/21339726/c468e8f8-c6c4-11e6-8f40-012fdb23bc8e.png">

**Comment by hbseo** [comment]
[134f9a73c7532eaa190e80144d190c21f09bdc56]
Thank you for finding the error.
I just fixed it.
