### ISSUE TITLE
단축키 구현을 하고 싶다

### ISSUE THREAD

**Issue by hellogaon** [alchon/simpsons#9]
1을 누르면 1이 뜨게
현재 그 버튼을 누르면 그 숫자가 위에 뜨는데 그 키보드 번호를 넣어도 뜨게

**Comment by hbseo** [comment]
다른거 다 구현하고 나중에 ㄱㄱ

**Comment by hbseo** [comment]
[20161202]
~ing

**Comment by hbseo** [comment]
[20161203]
I did some KeyEvent.
But I have a problem.
The first time We start, We must click with our mouse to activate keyboard input.
